//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.SoulBreaks = new HashSet<SoulBreak>();
            this.AbilityTypes = new HashSet<AbilityType>();
            this.ItemTypes = new HashSet<ItemType>();
        }
    
        public string Name { get; set; }
        public string GameName { get; set; }
        public string ImageName { get; set; }
        public string JobName { get; set; }
        public Nullable<int> Health { get; set; }
        public Nullable<int> Attack { get; set; }
        public Nullable<int> Defense { get; set; }
        public Nullable<int> Magic { get; set; }
        public Nullable<int> Resistance { get; set; }
        public Nullable<int> Mind { get; set; }
        public Nullable<int> Accuracy { get; set; }
        public Nullable<int> Evade { get; set; }
        public Nullable<int> Speed { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<SoulBreak> SoulBreaks { get; set; }
        public virtual ICollection<AbilityType> AbilityTypes { get; set; }
        public virtual ICollection<ItemType> ItemTypes { get; set; }
    }
}
