//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Characters = new HashSet<Character>();
            this.Items = new HashSet<Item>();
        }
    
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public string TempName { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
