//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string Name { get; set; }
        public string GameName { get; set; }
        public int Rarity { get; set; }
        public string Effect { get; set; }
        public string SoulBreakName { get; set; }
        public Nullable<int> Attack { get; set; }
        public Nullable<int> AttackMax { get; set; }
        public Nullable<int> Defense { get; set; }
        public Nullable<int> DefenseMax { get; set; }
        public Nullable<int> Magic { get; set; }
        public Nullable<int> MagicMax { get; set; }
        public Nullable<int> Resistance { get; set; }
        public Nullable<int> ResistanceMax { get; set; }
        public Nullable<int> Mind { get; set; }
        public Nullable<int> MindMax { get; set; }
        public Nullable<int> Accuracy { get; set; }
        public Nullable<int> AccuracyMax { get; set; }
        public Nullable<int> Evade { get; set; }
        public Nullable<int> EvadeMax { get; set; }
        public int Id { get; set; }
        public string ImageName { get; set; }
        public string ItemTypeName { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual SoulBreak SoulBreak { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
