//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoulBreak
    {
        public SoulBreak()
        {
            this.Items = new HashSet<Item>();
        }
    
        public string Name { get; set; }
        public string CharacterName { get; set; }
        public int Gauge { get; set; }
        public string ImageName { get; set; }
        public string TempLink { get; set; }
        public string Effect { get; set; }
        public string Target { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
